version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx/
    depends_on:
      - mariadb
      - wordpress
#    restart: always
    volumes:
      - nx_wp_data:/var/www/html
    networks:
      - bridge-network-inception
    env_file:
      - $ROOT_DIRECTORY_INCEPTION/srcs/.env
    ports:
      - "443:443"
      - "80:80"
    mem_limit: 1G
    cpus: 0.5
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
#    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bridge-network-inception
    env_file:
      - $ROOT_DIRECTORY_INCEPTION/srcs/.env
      - $ROOT_DIRECTORY_INCEPTION/secrets/db_password.txt
      - $ROOT_DIRECTORY_INCEPTION/secrets/db_root_password.txt
    mem_limit: 5G
    cpus: 2.0
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
#    restart: always
    depends_on:
      - mariadb
    volumes:
      - nx_wp_data:/var/www/html/
    networks:
      - bridge-network-inception
    env_file:
      - $ROOT_DIRECTORY_INCEPTION/srcs/.env
      - $ROOT_DIRECTORY_INCEPTION/secrets/db_password.txt
      - $ROOT_DIRECTORY_INCEPTION/secrets/db_root_password.txt
      - $ROOT_DIRECTORY_INCEPTION/secrets/wp_root_password.txt
      - $ROOT_DIRECTORY_INCEPTION/secrets/wp_user_password.txt
    mem_limit: 1G
    cpus: 1.5
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

volumes:
  nx_wp_data:
    driver: local
    driver_opts:
      device: "/home/${USER}/data/wordpress"
      o: bind
      type: none
  db_data:
    driver: local
    driver_opts:
      device: "/home/${USER}/data/mariadb"
      o: bind
      type: none

networks:
  bridge-network-inception:
    driver: bridge
